_target_: src.networks.TransformerHP

d_model: 64
d_rnn: 256
d_inner: 128
d_k: 16
d_v: 16
n_head: 4
n_layers: 4
num_clusters: 1
num_types: 1
dropout: 0.1
smooth: 0.1
lr: 1e-4
integral_biased: True
use_additional_rnn: True
clustering_method: "kmeans"
