_target_: src.datamodules.thp_datamodule.THPDataModule

data_dir: ${data_dir}
data_config_yaml: ${data_config_file}
maxsize: null
maxlen: 300
train_val_split: 0.8
ext: "csv"
time_col: "time"
event_col: "event"
datetime: False
batch_size: 32
num_workers: 8
