_target_: src.datamodules.ts_datamodule.TsfreshDataModule

data_dir: ${data_dir} 
data_config_yaml: ${data_config_file}
maxsize: null
maxlen: 1000
ext: "csv"
time_col: "time"
event_col: "event"
feature_settings: "complete"
batch_size: 128
num_workers: 0
